### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by idkjs** [poeschko/reason-react-tictactoe#2]
If you download, npm install, npm run build, the project doesn't run. Just an FYI, I was trying to understand glamor in reason.  Are you aware of any other examples?

```
[1/3] Building src/Board.cmj
FAILED: src/Board.cmj /Users/shingdev/code/REASON/reason-react-tictactoe-master/lib/js/src/Board.js src/Board.cmi
/Users/shingdev/code/REASON/reason-react-tictactoe-master/node_modules/bs-platform/bin/bsc.exe -bs-package-name reason-react-tictactoe  -bs-package-output commonjs:lib/js/src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include -I /Users/shingdev/code/REASON/reason-react-tictactoe-master/node_modules/reason-react/lib/ocaml -I /Users/shingdev/code/REASON/reason-react-tictactoe-master/node_modules/bs-glamor/lib/ocaml -I src  -w -30-40+6+7+27+32..39+44+45 -nostdlib -I '/Users/shingdev/code/REASON/reason-react-tictactoe-master/node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -bs-re-out -bs-super-errors -o src/Board.cmj -c  src/Board.mlast

  We've found a bug for you!
  /Users/shingdev/code/REASON/reason-react-tictactoe-master/src/Board.re 3:6-11

  1 │ open Game;
  2 │
  3 │ open Glamor;
  4 │
  5 │ module Board = {

  The module or file Glamor can't be found.

  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?

ninja: build stopped: subcommand failed.
>>>> Finish compiling(exit: 1)
```

**Comment by safhac** [comment]
not sure if this is a separate issue

 node 10.1.0, 64 bit win 10
`npm install` fails 
```
C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\jscomp\others>cd ..
Installing
C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\jscomp\runtime\block.cmj -----> C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\lib\ocaml\block.cmj
fs.js:148
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:148:11)
    at Object.fs.rename (fs.js:694:14)
    at renameAsync (C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\scripts\build_util.js:34:8)
    at C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\scripts\build_util.js:94:6
    at Array.forEach (<anonymous>)
    at Object.install (C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\scripts\build_util.js:82:11)
    at Object.<anonymous> (C:\Users\Dell\source\reasonml\reason-react-tictactoe\node_modules\bs-platform\scripts\install.js:135:20)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
